version: "3.8"
services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: dolbomon-mqtt
    ports: ["1883:1883","9001:9001"]
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mqtt-data:/mosquitto/data
      - mqtt-log:/mosquitto/log

  hub:
    image: node:20-alpine
    container_name: dolbomon-hub
    working_dir: /app
    depends_on: [mqtt]
    ports: ["8080:8080"]
    env_file: .env
    volumes:
      - ./hub:/app
      - ./hub/db:/app/db
    command: sh -c "npm i && node index.js"

  # 선택: USB Zigbee 동글 사용 시 활성화
  z2m:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    depends_on: [mqtt]
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./z2m:/app/data
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0
    network_mode: host
    profiles: ["zigbee"]
volumes:
  mqtt-data:
  mqtt-log: